---
config_info:
  name: sample
config:
  controllers:
  - name: test
    active: true
    remote: false
    url: 
    neopixels:
      led_count: 120
      max_brightness: 255
      pin: 18
      max_watts: 50
      watts_per_60: 18
      grb: false
      flipped: false
    settings:
      initial_brightness: 200
  - name: remote_test
    active: true
    remote: true
    url: localhost:5000
    # url: rpi3.kinsaurralde.com:5000
    neopixels:
      led_count: 60
      max_brightness: 255
      pin: 18
      max_watts: 18
      watts_per_60: 18
      grb: false
      flipped: true
    settings:
      initial_brightness: 200