---
config_info:
  name: sample
config:
  controllers:
  - name: test
    active: true
    remote: false
    url: 
    neopixels:
      led_count: 60
      max_brightness: 255
      pin: 18
      max_watts: 50
      grb: false
      flipped: false
    settings:
      initial_brightness: 200
  - name: remote_test
    active: true
    remote: true
    url: url.com
    neopixels:
      led_count: 30
      max_brightness: 255
      pin: 18
      max_watts: 10
      grb: false
      flipped: true
    settings:
      initial_brightness: 200