---
config_info:
  name: sample
config:
  web:
    port: 5000
  config_paths:
    controllers: 'configs/sample/controllers.yaml'
    quick_actions: 'configs/sample/quick_actions.yaml'
    virtual_controllers: 'configs/sample/virtual_controllers.yaml'
    colors: 'configs/sample/colors.yaml'
