---
alias:
  all:
    - tester_a_0
    - tester_a_1
    - tester_b_0
    - tester_b_1
    - tester_c_0
  a:
    - tester_a_0
    - tester_a_1
  b:
    - tester_b_0
    - tester_b_1
  c:
    - tester_c_0
controllers:
  - name: tester_a_0
    url: http://localhost:6000
    strip_id: 0
    init:
      num_leds: 300
      milliwatts: 5000
      brightness: 100
      grb: false
    active: 'active'
  - name: tester_a_1
    url: http://localhost:6000
    strip_id: 1
    init:
      num_leds: 300
      milliwatts: 5000
      brightness: 100
      grb: false
    active: 'active'
  - name: tester_b_0
    url: http://localhost:6001
    strip_id: 0
    init:
      num_leds: 300
      milliwatts: 100
      brightness: 100
      grb: false
    active: 'disabled'
  - name: tester_b_1
    url: http://localhost:6001
    strip_id: 1
    init:
      num_leds: 300
      milliwatts: 100
      brightness: 100
      grb: false
    active: 'disabled'
  - name: tester_c_0
    url: http://localhost:6002
    strip_id: 0
    init:
      num_leds: 240
      milliwatts: 5000
      brightness: 100
      grb: false
    active: 'active'
