---
sequences:
  - name: test
    module: sequences.sample
    functions:
      - test_a
      - test_b
      - test_c
      - test_d
      - test_e
      - test_invalid
    active: true
  - name: christmas
    module: sequences.christmas
    functions:
      - basic
    active: true
