devices:
  - name: rpi2
    user: pi
    hostname: 10.0.0.107
    # hostname: rpi2.kinsaurralde.com
    remote: false
    path: Files/lights/
    ssh: ~/.ssh/rpi2
  - name: rpi3_remote
    user: pi
    hostname: 10.0.0.108
    # hostname: rpi3.kinsaurralde.com
    remote: true
    path: Files/lights/
    ssh: ~/.ssh/rpi3
