---
config_info:
  name: generated
config:
  web:
    port: 5000
  config_paths:
    controllers: 'configs/generated/controllers.yaml'
    quick_actions: 'configs/generated/quick_actions.yaml'
    virtual_controllers: 'configs/generated/virtual_controllers.yaml'
    colors: 'configs/generated/colors.yaml'
    animations: 'configs/generated/animations.yaml'
