---
- userhost: pi@rpi4.kinsaurralde.com      # user@hostname
  key: "~/.ssh/rpi4"                      # path to ssh key
  destination: "Files/test_rgb/"          # folder that files should be put into
  webapp: false                           # include webapp compenent
  controller: true                        # include controller component